include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    avoid_print: false
    # Relax noisy rules to keep CI clean for now.
    unnecessary_brace_in_string_interps: false
    unnecessary_string_interpolations: false
    use_build_context_synchronously: false
    deprecated_member_use: false
